#!/bin/bash
# Script pipeline to perform the comparison between ExploreDTI, Eddy and TORTOISE softwares

usage(){
  echo "  This scrip pipeline to perform the comparison between ExploreDTI, Eddy and TORTOISE softwares."
  echo "  Usage: $0 <DTI volume>"
  echo ""
}

if [[ $# -eq 0 ]]; then
  usage
  exit
fi

# Tomar de entrada: imagem phantom com e sem distorcai ec - Imagem sem distorcao eh a referencia
# Aplicar o pipeline de processamento de cada um dos softwares
# Calcular valores quantitativos da imagem residual (sub com e sem ec) - Emitir uma tabela com os valores ...ficar mais facil de plotar no Matlab ou Origin
