#!/bin/bash
# Script pipeline to perform the comparison between ExploreDTI, Eddy and TORTOISE softwares

usage(){
  echo "  This scrip pipeline to perform the comparison between ExploreDTI, Eddy and TORTOISE softwares."
  echo "  Usage: $(basename $0) <DTI volume> <T1 volume> <Type of experiment [eddy,tortoise,exploredti]>"
  echo ""
}

if [[ $# -eq 0 ]]; then
  usage
  exit
elif [[ $# -lt 3 ]]; then
  usage
  exit
fi

# Data
DTI_VOL=$1
T1_VOL=$2
TYPE_EXP=$3

HOME_PATH=`echo ~`

if [[ `ls ~ | grep "DTI_STUDY"` == "" ]]; then  
  mkdir ${HOME_PATH}/DTI_STUDY
  mkdir ${HOME_PATH}/DTI_STUDY/TORTOISE
  mkdir ${HOME_PATH}/DTI_STUDY/Eddy
  mkdir ${HOME_PATH}/DTI_STUDY/ExploreDTI
  mkdir ${HOME_PATH}/DTI_STUDY/ExploreDTI/nandata
  mkdir ${HOME_PATH}/DTI_STUDY/ExploreDTI/expdtidata
  mkdir ${HOME_PATH}/DTI_STUDY/ExploreDTI/dwidata
fi
BASE_FOLDER="$HOME_PATH/DTI_STUDY"


# Tomar de entrada: imagem phantom com e sem distorcai ec - Imagem sem distorcao eh a referencia
# Calcular valores quantitativos da imagem residual (sub com e sem ec) - Emitir uma tabela com os valores ...ficar mais facil de plotar no Matlab ou Origin

case $TYPE_EXP in
  "eddy" )
	echo "	==> Performing EDDY correction pipeline..."
	EDDY_ROOT="$BASE_FOLDER/Eddy"
	source eddy_pipeline $EDDY_ROOT $DTI_VOL
    ;;
  "tortoise" )
	echo "	==> Performing TORTOISE correction pipeline..."
	TORTOISE_ROOT="$BASE_FOLDER/TORTOISE"
	source tortoise_prepvm $TORTOISE_ROOT $DTI_VOL $T1_VOL
    ;;
  "exploredti" )
	echo "	==> Performing ExploreDTI correction pipeline..."
	EXPDTI_ROOT="$BASE_FOLDER/ExploreDTI"
	source exploredti_pipeline $EXPDTI_ROOT $DTI_VOL $T1_VOL
    ;;
esac

#========================================
## Processing with TORTOISE dr_buddi_vm
#
#========================================
